### PR TITLE
Add @value to context when iterating over maps/iterables

### PR DESCRIPTION
**Pull request by giflw**
Add @value to context to more semantic the access to map key/value pairs

### CODE REVIEW

**Comment by jknack** [comment]
Hello @giflw thanks for your pull. Is this supported by handlebarsjs?

If so, then can you please add a two test: one with list input the other with a hash/map input.

**Comment by giflw** [comment]
Hi @jknack . I have no idea if this is supported on JS. I was just using the Java version now, and seems to me that it would be semantically better than using {{this}} to access the value of the map entry.

**Comment by jknack** [comment]
Yea, just tried at http://tryhandlebarsjs.com/ and isn't supported by handlebars.js

This creates incompatibilities between the two implementations so don't think is a good idea to add this for now.

That's being said, let's keep this pull open and if more users find it valuable then I will merge.

Thanks again.

**Comment by giflw** [comment]
Maybe this change can be made in JS version too. I just need to have a little more time to do that. I think this is the file that need to be modified: https://github.com/wycats/handlebars.js/blob/e8ceafa6525a5d41a20aa74dfe24bf99d0bc2fcd/lib/handlebars/helpers/each.js. This way, there will be no incompatibilities.

**Comment by jknack** [comment]
That will be ideal, yes!

**Comment by giflw** [comment]
I made a proposal there https://github.com/wycats/handlebars.js/pull/1253.

**Comment by jknack** [comment]
Rejected as explained in related handlebars.js issue

**Pull request closed without merging**
