### PR TITLE
Fix #1018 with automatic module name 4.x

### LINKED ISSUE #1018: java modules: modularize handlebars modules

### PR DESCRIPTION
**Pull request by agentgt**
This pr is on the 4.x branch as the master branch should use proper module-info.

### CODE REVIEW

**Review by Montimur — COMMENTED** [review]
This approach to setting automatic module names looks great to me. This should work as long as none of the submodules overwrite the `maven-jar-plugin`. Additionally, it appears that each submodule overwrites the `<module.name>` property, ensuring that each submodule will have a unique automatic module name in their manifest. However, I wonder if 'module.name' shows an "UnresolvedMavenProperty" warning due to `<module.name>` not being defined in the parent POM file. Shouldn't we add a `<!--suppress UnresolvedMavenProperty` above the line `<Automatic-Module-Name>${project.groupId}.${module.name}</Automatic-Module-Name>`?

**Comment by agentgt** [comment]
To be fair I did the above in vim and did not check IDE or compiling a parent pom module alone.

As for the unresolved I think a dummy module name should work?


I believe for 5.x @jknack will go full modular (module-info)

**Comment by Montimur** [comment]
Wow, I applaud you for using vim for this. I think using an IDE like IntelliJ has made me, well... lazy. Yes, a dummy module name should work in the parent pom; it will be ignored. If @jknack does go full modular in 5.x, then that would solve the problem I am having with my modular application.  Anyway, I appreciate your response and the time you've taken to read this, @agentgt. Happy coding.

**Comment by agentgt** [comment]
@Montimur oh I just used it because even at 32 gigs of memory I run out ([well actually it is more like my music starts popping](https://www.reddit.com/r/macbookpro/comments/vluqp9/psa_suffering_from_your_m1_macbook_pro_making/) )

I normally use IDEs all the time.

**Comment by jknack** [comment]
See #1018

**Pull request closed without merging**
