### PR TITLE
Issues/667/illegal access 2

### LINKED ISSUE #667: WARNING: Illegal reflective access by com.github.jknack.handlebars.context.MemberValueResolver
I've been working on migrating some projects from java 8 to java 11. As I was compiling, I noticed a warning in the log:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.MemberValueResolver (../.m2/repository/com/github/jknack/handlebars/4.1.2/handlebars-4.1.2.jar) to method java.util.Collections$EmptyMap.isEmpty()
WARNING: Please consider reporting this to the maintainers of com.github.jknack.handlebars.context.MemberValueResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

So, I figured I'd create an issue and make sure you're aware. It works with java 11...not sure what will happen with java 12 which should be released March 2019.

### PR DESCRIPTION
**Pull request by agentgt**
This PR will hopefully fix #667 

Let me know if it looks good and I will squash the commits.

I added some maven parameters so that the build log wasn't so long. You can admit that change if you like.

### CODE REVIEW

**Comment by jknack** [comment]
> I added some maven parameters so that the build log wasn't so long.

Thanks going to give it a try.

I was under the impression we should:

- check for public field/method on Java 9+ or throws an exception
- keep as it is on Java 8

**Comment by agentgt** [comment]
> I was under the impression we should:
> check for public field/method on Java 9+ or throws an exception
keep as it is on Java 8

The problem is a lot of people post Java 9 used the command line parameter  `--illegal-access` to allow it to happen.

If you just blindly not allow caching of the non public members their code will fail (and probably very bizarre ways and not easy to find).

Regardless you still can't call `setAccessible` on public members if the concrete class is private. That is why the `isEmpty` problem is happening. That is you can't just check if the member is public.

Technically the `members` method in MemberValueResolver could also be updated like  below code snipper but that again would break existing users that use the flag to access protected/private members that are between JDK 15 and JDK 9 (inclusive for both). I believe 16 even with command line your off limits to the JDK modules but I have to double check that.

```java

	protected void members(
			final Class<?> clazz,
			final Set<Method> members) {
		if (clazz != Object.class) {
			// Keep backing up the inheritance hierarchy.
			if (Modifier.isPublic(clazz.getModifiers()) || Modifier.isProtected(clazz.getModifiers())) {
				@NonNull
				Method[] methods = clazz.getDeclaredMethods();
				for (Method method : methods) {
					if (Modifier.isPublic(method.getModifiers()) && isValid(method)) {
						members.add(method);
					}
				}
			}
			Class<?> sc;
			if ((sc = clazz.getSuperclass()) != null) {
				members(sc, members);
			}
			for (Class<?> superIfc : clazz.getInterfaces()) {
				members(superIfc, members);
			}
		}
	}

```

Ideally you would do the above filtering and never call `setAccessible` on JDK 16 or higher but it was more complexity than I wanted to add for this initial fix.

**Comment by jknack** [comment]
Got it. Let's go with this for now.

**Comment by agentgt** [comment]
In our code base version of `MemberValueResolver` I also changed the cache to:

```java
	private final Map<Class<?>, Map<String, Entry<Method, Optional<MethodHandle>>>> cache = new ConcurrentHashMap<>();

	private final boolean useMethodHandle;

	private final @Nullable Lookup lookup;
```

And had a flag to enable using method handles and updated cache method like:

```java
	private Map<String, Entry<Method, Optional<MethodHandle>>> cache(
			final Class<?> clazz) {
		Map<String, Entry<Method, Optional<MethodHandle>>> mcache = this.cache.get(clazz);
		if (mcache == null) {
			mcache = new HashMap<>();
			Set<Method> members = members(clazz);
			for (Method m : members) {
				// Mark as accessible.
				// if (m instanceof AccessibleObject) {
				// ((AccessibleObject) m).setAccessible(true);
				// }
				List<String> memberNames = memberNames(m);
				if (!memberNames.isEmpty()) {
					MethodHandle mh = null;
					Lookup lookup = this.lookup;
					if (isUseMethodHandle() && lookup != null) {
						try {
							mh = lookup.unreflect(m);
						}
						catch (IllegalAccessException e) {
							throw new IllegalStateException("Could not access using MethodHandle. method: " + m, e);
						}
					}
					Entry<Method, Optional<MethodHandle>> e = Map.entry(m, Optional.ofNullable(mh));
					for (String mn : memberNames) {
						mcache.put(mn, e);
					}
				}
			}
			this.cache.put(clazz, mcache);
		}

		return mcache;
	}
```

But I figured that was too big a change to make.

**Comment by jknack** [comment]
yea, not sure. next release 4.3.0 is suppose to break a few things (like guava) and bring better support for java 9+.

so probably is time to add something like that

**Review by jknack — APPROVED** [review]
let's squash

**Comment by agentgt** [comment]
Squashed. I kept the Maven command line changes as well in the github workflow. I rarely need to see the progress of downloads but feel free to change that.

**Pull request merged**
