### PR TITLE
Invoke default methods on Type Safe template interfaces

### LINKED ISSUE #515: The TypeSafeTemplate proxy and Java 8 default methods
I had a case where I wanted to add some default methods to a TypeSafeTemplate sub-interface, but soon found that it would require the cooperation of the proxy implementation to detect and delegate to such default methods. There is a way to call default methods given just an interface, but it requires a bit of gymnastics and isn't particularly pretty.

Here's an example:

```java
interface UserTemplate extends TypeSafeTemplate<User> {

    UserTemplate setName(String name);

    UserTemplate setAge(int age);

    /* ... */

    default String render(User context) {
        try {
            return apply(context);
        } catch (IOException exc) {
            // Writing to a string shouldn't have caused an IOException...
            throw new UncheckedIOException("Unexpected exception", exc);
        }
    }

}

/* ... */

UserTemplate template = handlebars.compile("{{name}}").as(UserTemplate.class);
template.render(user);

```

If you think this would be useful, and worth the minor increase in LoC and complexity in the TypeSafeTemplate proxy implementation, I'll open a PR.

### PR DESCRIPTION
**Pull request by kilink**
This resolves #515. I am a bit unsure how to include a test for this, since the source/target Java versions are set to 7 in the pom.xml. Maybe using Animal Sniffer?

### CODE REVIEW

**Comment by jknack** [comment]
Animal Sniffer looks good

**Comment by jknack** [comment]
Are we good here? Should I wait before making a release? Would like to release `4.0.6` today

**Comment by kilink** [comment]
The only thing missing is the unit tests, which are written already - I just haven't had a chance to look into using animal sniffer, since those tests necessarily use Java 8 only features. I might be able to wrap that up tonight.

**Comment by kilink** [comment]
Okay, I've added a basic test that exercises the new feature, namely the ability to call a default method of a type safe template.

I created a sub-package handlebars-jdk8-tests, and a jdk8 profile that gets activated automatically when the JDK is >= 1.8.

Not sure what's going on with coveralls.

**Pull request merged**
