### PR TITLE
Update Handlebars.js to 4.0.4 and make default

### PR DESCRIPTION
**Pull request by karlhorky**

### CODE REVIEW

**Comment by karlhorky** [comment]
Ah, I forgot to update the tests for the `PrecompileHelper`. One minute.

**Comment by jknack** [comment]
I'm cool with this, but we need to "collect" new feature of 4.x (think from 3.x too).

Anyway, next release of handlebars.java 3.0.0 will use hbs.js 4.x

**Comment by karlhorky** [comment]
@jknack Yeah, I agree. Compiling the list will take a bit of work, since the [release notes](https://github.com/wycats/handlebars.js/blob/master/release-notes.md) don't clearly mention which things are features and which are fixes.

@husayt did include a list of missing Handlebars.js 3.0 features [here](https://github.com/jknack/handlebars.java/issues/349#issuecomment-96656927), so that's a start.

**Comment by jknack** [comment]
I missed the comment from @husayt ! I will try to file some of those as issues (not all make sense for handlebars.java)

**Comment by karlhorky** [comment]
I've added some issues for v4: https://github.com/jknack/handlebars.java/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Akarlhorky+v4+

**Comment by jknack** [comment]
@karlhorky thanks! Think is time to sync handlebars.js version number with handlebars.java, what do you think?

Also, let me know if you can work on any of the issues of v4 (will appreciate :)

**Comment by karlhorky** [comment]
No problem. Yeah, I think the best would be to sync the version numbers.

I'll see if I can find some time to do some issues, although I don't have much experience with Java.

**Comment by karlhorky** [comment]
Finally green!

**Comment by husayt** [comment]
Excellent, I will be happy to do comparative testing, as we use both java and js versions to run the same templates.

**Comment by jknack** [comment]
I missed this pull, my bad :S

But is done at #443

**Comment by karlhorky** [comment]
No problem, thanks.

**Pull request closed without merging**
