### PR TITLE
An initial look at Handlebars.java on JDK17/Spring 6/Jakarta EE

### PR DESCRIPTION
**Pull request by jcputney**
@jknack I don't know if you're interested in moving in this direction with the project just yet, but I wanted to take an initial look at getting it compatible with JakartaEE 10, since that is where most of the major server providers are heading. Obviously, this is a breaking change for anyone that isn't on a compatible server yet, but thought it would be worth looking in that direction. Thanks for all the hard work!

### CODE REVIEW

**Comment by jcputney** [comment]
@jknack any help you need with this project? This PR is what's preventing Handlebars.java from being usable with the latest versions of the Eclipse Krazo Jakarta MVC implementation. I'm just wondering if I need to start looking into a different templating system for my projects. Thanks!

**Comment by cricketbackground** [comment]
@jcputney @jknack 

I'm upgrading my project from spring boot 2.6.6 to spring boot 3.0. Realized handlebars.java is not compatible as it still uses javax.* packages. In spring boot 3.0 the package changed to jakarta.* 

Can you please expedite this PR merge and release?

**Comment by DevTomek-pl** [comment]
@cricketbackground @jcputney @jknack any updates? Can you release these changes?

**Comment by jcputney** [comment]
@cricketbackground @DevTomek-pl for anyone looking to use this in their project, you can use the following from the jitpack.io repository:

```xml
<dependency>
    <groupId>com.github.jcputney.handlebars-java</groupId>
    <artifactId>handlebars</artifactId>
    <version>jakarta-ee-update-SNAPSHOT</version>
</dependency>
```

and

```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

No ideal, but it's working just fine for us, since this project appears to be mostly abandoned.

**Comment by jknack** [comment]
done in 4.4.0

**Pull request closed without merging**
