### PR TITLE
Add a ValueResolver for fluent interfaces

### PR DESCRIPTION
**Pull request by tlovett-rmn**
We're using fluent interface getters and setters, like so:
```java
public class Foo {
    private String bar;

    public String bar() {
        return this.bar;
    }
    public Foo bar(final String bar) {
        this.id = id;
        return this;
    }
}
```
Here's the ValueResolver we wrote for them. Please review the tests. I added a couple, but it wasn't clear to me to which of the existing methods I should add the FluentInterfaceValueResolver. Please decline this PR with suggestions for where to create more tests or which tests to expand upon :)

### CODE REVIEW

**Comment by jknack** [comment]
like this, but I do have a question. isn't the MethodValueResolver enough? probably not bc of the name clash... not sure... but if not can you try to modify MethodValueResolver instead? That would be great and we wont need a new value resolver :)

**Comment by tlovett-rmn** [comment]
The MethodValueResolver as is is not sufficient because it doesn't check that the [parameter count for the method is 0](https://github.com/tlovett-rmn/handlebars.java/blob/1a4bbc7508e68947259ebdcbe2f0a467671921dc/handlebars/src/main/java/com/github/jknack/handlebars/context/FluentInterfaceValueResolver.java#L39-L40). So for fluent interfaces it will attempt to invoke the setter as a getter, which throws `IllegalArgumentException: wrong number of arguments`. It also doesn't check that the method is not static.

Since JavaBeanValueResolver also checks `parameterCount == 0`, it should be safe to pull that check up into `MethodValueResolver` and add the `super.matches(method, name)` check to `JavaBeanValueResolver`. The `isPublic` check could then be removed too. Should I do that?

Adding the `parameterCount == 0` to `MethodValueResolver` is only sort of backwards-compatible though. In cases where the user would have gotten an `IllegalArgumentException` they will instead silently have no matches. I think this might actually be closer to what the spec says should happen when a {{name}} doesn't exist in the context:

>If there is no name key, the parent contexts will be checked recursively. If the top context is reached and the name key is still not found, nothing will be rendered.

I think the `isStatic` check can be safely dropped, since once could theoretically have fluent getters and setters for a static member variable.

**Should I go ahead and the `parameterCount == 0` check to `MethodValueResolver`?**

**Comment by jknack** [comment]
yes, go for it.

MethodValueResolver is used as zero-arg, bc we can't make a call to a method with args from mustache/handlebars. So, we can safely add the param count check there now.

Do all the changes you need into MethodValueResolver, just make sure JavaBeanResolver works as today.

cool?

**Comment by tlovett-rmn** [comment]
cool :+1:

**Comment by tklovett** [comment]
Hey @jknack - I just upgraded a project to the latest v2.2.1 and, after some digging, found out that this PR somehow didn't make it into master. It's parent commit on master (fa77c3) is there but there 0b1b123 is not. Could you merge it in again and do another release?

**Comment by jknack** [comment]
sorry, I screw up at some point. I restored the commit and push it. will release 2.2.2 right now and will be available in central in the next 2/3 hours

glad you catch it

**Comment by tklovett** [comment]
No worries, thanks for the quick response!

**Pull request merged**
