### PR TITLE
Fix for issue #403

### PR DESCRIPTION
**Pull request by erdi**
Contains a test and a fix for the cache in `MethodValueResolver` to handle members of the same class loaded by distinct class loaders.

### CODE REVIEW

**Comment by erdi** [comment]
Let me fix these checkstyle violations which are causing the build to fail. I though that getting the tests to pass was enough. :)

**Comment by erdi** [comment]
Done, but I would argue that requiring javadoc comments even for private (!) members is a bit over the top.

**Comment by erdi** [comment]
@jknack is there anything else I should do to get this PR accepted?

**Comment by erdi** [comment]
thx!

**Comment by jknack** [comment]
np, been busy with jooby but will try to make a release of handlebars.java next week

**Pull request merged**
